# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import studentinfo_pb2 as studentinfo__pb2


class StudentInfoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/studentinfo.StudentInfo/Add',
                request_serializer=studentinfo__pb2.StudentRequest.SerializeToString,
                response_deserializer=studentinfo__pb2.StudentResponse.FromString,
                )
        self.QueryByID = channel.unary_unary(
                '/studentinfo.StudentInfo/QueryByID',
                request_serializer=studentinfo__pb2.StudentByIDRequest.SerializeToString,
                response_deserializer=studentinfo__pb2.StudentRequest.FromString,
                )
        self.QueryByName = channel.unary_unary(
                '/studentinfo.StudentInfo/QueryByName',
                request_serializer=studentinfo__pb2.StudentByNameRequest.SerializeToString,
                response_deserializer=studentinfo__pb2.StudentsResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/studentinfo.StudentInfo/Delete',
                request_serializer=studentinfo__pb2.StudentByIDRequest.SerializeToString,
                response_deserializer=studentinfo__pb2.StudentResponse.FromString,
                )


class StudentInfoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudentInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=studentinfo__pb2.StudentRequest.FromString,
                    response_serializer=studentinfo__pb2.StudentResponse.SerializeToString,
            ),
            'QueryByID': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryByID,
                    request_deserializer=studentinfo__pb2.StudentByIDRequest.FromString,
                    response_serializer=studentinfo__pb2.StudentRequest.SerializeToString,
            ),
            'QueryByName': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryByName,
                    request_deserializer=studentinfo__pb2.StudentByNameRequest.FromString,
                    response_serializer=studentinfo__pb2.StudentsResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=studentinfo__pb2.StudentByIDRequest.FromString,
                    response_serializer=studentinfo__pb2.StudentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'studentinfo.StudentInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StudentInfo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/studentinfo.StudentInfo/Add',
            studentinfo__pb2.StudentRequest.SerializeToString,
            studentinfo__pb2.StudentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/studentinfo.StudentInfo/QueryByID',
            studentinfo__pb2.StudentByIDRequest.SerializeToString,
            studentinfo__pb2.StudentRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/studentinfo.StudentInfo/QueryByName',
            studentinfo__pb2.StudentByNameRequest.SerializeToString,
            studentinfo__pb2.StudentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/studentinfo.StudentInfo/Delete',
            studentinfo__pb2.StudentByIDRequest.SerializeToString,
            studentinfo__pb2.StudentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
